### PR TITLE
Configure data_flow_config repository for NF

### PR DESCRIPTION
**Pull request by cconrad8**

### CODE REVIEW

**Comment by cconrad8** [comment]
@lakikowolfe I added the configuration and the example schema - this should be a good starting place I think for NF!

**Review by lakikowolfe — APPROVED** [review]
This looks good!

**Comment by lakikowolfe** [comment]
> @lakikowolfe wondering if there's a timeline to complete this PR - or just when we could start to have a demo that is closer to NF specific that we can present to our funders? Thanks!

@cconrad8 I can merge this PR now. I will have to create the Data Flow Manifest next. The work is being tracked in [FDS-1494](https://sagebionetworks.jira.com/browse/FDS-1494). I will push to get it added to the next sprint (2/6-2/19)!

**Comment by cconrad8** [comment]
> > @lakikowolfe wondering if there's a timeline to complete this PR - or just when we could start to have a demo that is closer to NF specific that we can present to our funders? Thanks!
> 
> @cconrad8 I can merge this PR now. I will have to create the Data Flow Manifest next. The work is being tracked in [FDS-1494](https://sagebionetworks.jira.com/browse/FDS-1494). I will push to get it added to the next sprint (2/6-2/19)!

Thanks a bunch!

**Pull request merged**
